### ISSUE TITLE
Ponyfill?

### ISSUE THREAD

**Issue by simevidas** [Kikobeats/array-future#3]
> Ponyfill: A polyfill that doesn't overwrite the native method.

I don’t understand your definition. Polyfills do not overwrite native methods. They only define API if it’s not already present (in the browser).

**Comment by Kikobeats** [comment]
[sindresorhus](https://twitter.com/sindresorhus) is the author of the definition and I think that is related that you commonly isolate the dependency in library and use it, but, this is different: first check if exists the native implementation:

https://github.com/Kikobeats/array-future/blob/master/index.js#L7

**Comment by simevidas** [comment]
As I said, all polyfills do that. They check if an API exists, and only if not, they implement it in JavaScript. It looks like Sindre’s ponyfills are stand-alone packages that are not assigned to any of the built-in objects. The user instead assigns them to one of the application’s dynamic variables or objects.

Since you're assigning to `Array.prototype`, your API is not a ponyfill. It’s actually a prollyfill, which is a polyfill but for proposed API that hasn’t been standardized yet. No joke :)

**Comment by Kikobeats** [comment]
really? sounds interesting! any source of this please? :-)

**Comment by simevidas** [comment]
https://twitter.com/slexaxton/status/257543702124306432

**Comment by Kikobeats** [comment]
@simevidas I'm going to change it for the next tag :-)
