### ISSUE TITLE
Added Array.observe and Array.unobserve

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/array-future#4]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/observe

**Comment by mk-pmb** [comment]
Mozilla abandoned it and suggest to use a Proxy instead, is that the better option?

**Comment by Kikobeats** [comment]
why mozilla? :(

**Comment by mk-pmb** [comment]
Either I don't understand your question, or the answer is "because that's where the link points". To me it looked like you described a proposal for X by linking to a site that (nowadays) says X is deprecated, don't use it.

**Comment by Kikobeats** [comment]
yes, you're, simply I was thinking about why mozilla deprecated this feature 😄
