### ISSUE TITLE
ES7 Proposal

### ISSUE THREAD

**Issue by mikehayesuk** [Kikobeats/array-future#7]
Are any of these methods actually proposed for ES7?

I've taken a look at the proposals [here](https://github.com/tc39/ecma262) and [here](https://github.com/tc39/ecma262/blob/master/stage0.md) but cannot find any mention of additional array methods. Searching Google doesn't really bring anything up either.

I think some of these methods are so common that there should be a proposal but it doesn't look like there is anything "real" yet.

Thanks

**Comment by Kikobeats** [comment]
Actually is not a formal ES7 proposal, just a library with the methods that I would like to be included in ES7 and a personal playground.

Yes, some of these are very common, but currently are not present natively and you need to write a wrapper all the time until the end of the life in the universe. So I prefer use it!
